export const initialForm = {
  nama: "",
  phone: "",
  email: "",
  budget: "",
  tanggal: "",
  tanggalFleksibel: false,
  durasi: "",
  meetingPoint: "",
  catatan: "",
  tripType: "custom",
  customTripName: "",
  selectedDestinasi: null,
  tripFrom: "Individu",
  namaInstitusi: "",
  jumlahPeserta: "",
  transportNeeds: "",
  standarPenginapan: "",
  layananTambahan: [],
  metodeKontak: "whatsapp",
};

